### ISSUE TITLE
We should use capacitor-assets, not cordova-res, no?

### ISSUE THREAD

**Issue by ddurham2** [ionic-team/capacitor-docs#121]
**URL**
The URL at which the content is missing or inaccurate
https://capacitorjs.com/docs/guides/splash-screens-and-icons

**What is missing or inaccurate about the content on this page?**
I was having trouble getting the Android app icon to update properly in an ionic-capacitor app and was following the instructions above.
Then I found these issues: 
- https://github.com/ionic-team/capacitor-assets/issues/164
- https://github.com/ionic-team/capacitor-assets/issues/173
- https://github.com/ionic-team/capacitor-assets/issues/165#issuecomment-1264736353

Which leads me to believe that [this source file for the above doc page](https://github.com/ionic-team/capacitor-docs/blob/main/docs/main/guides/splash-screens-and-icons.md) is outdated and should actually instruct the user to use capacitor-assets rather than cordova-res, correct?

If I'm correct in this assessment, I'll make the needed PR.

**Comment by dtarnawsky** [comment]
@ddurham2 , docs are updated to use capacitor assets and this issue can be closed

**Comment by Martin-Eckleben** [comment]
Should be done for V4 as well I think?
I use V4 and probably used the wrong generation tool for a while having problems.

https://capacitorjs.com/docs/v4/guides/splash-screens-and-icons
