### ISSUE TITLE
Broken links and images for React & Angular in docs page

### ISSUE THREAD

**Issue by ezekiel747** [ionic-team/capacitor-docs#124]
**URL**
https://capacitorjs.com/docs/main/deployment/progressive-web-app

There are broken links and images for React & Angular on this docs page.

**Comment by jcesarmobile** [comment]
Thanks for the issue
looks like that page should be in Capacitor docs since it's a copy of this page from Ionic docs
https://ionicframework.com/docs/deployment/progressive-web-app

In the Ionic page images and links work
