### ISSUE TITLE
Capacitor Android Plugin Guide is outdated, it still use fn tha

### ISSUE THREAD

**Issue by JordenLCH** [ionic-team/capacitor-docs#137]
**URL**
https://capacitorjs.com/docs/v2/plugins/android#export-to-capacitor

**What is missing or inaccurate about the content on this page?**
It is still using an out-of-date function that no longer works.

```this.init()``` should change to ```registerPlugin(FirebaseAnalytics.class);```

https://github.com/capacitor-community/firebase-analytics/issues/94
https://capacitorjs.com/docs/updating/3-0#switch-to-automatic-android-plugin-loading

**Comment by jcesarmobile** [comment]
You are checking v2 version of the plugins
v4 version of the same docs is located at https://capacitorjs.com/docs/plugins/android (see, no v2 on the url)
