### ISSUE TITLE
Implement custom android plugin issue

### ISSUE THREAD

**Issue by VashAlex** [ionic-team/capacitor-docs#138]
When I tried to implement my own plugin I just copied and paste all code from example
https://capacitorjs.com/docs/android/custom-code
But seems this call.resolve(ret) does not work, and I could not get any data in my js file. Did I miss something?

<img width="819" alt="Screenshot 2023-01-20 at 14 05 20" src="https://user-images.githubusercontent.com/47140236/213691142-1e02c369-f0f7-4e02-ac5c-cfd88bced3a0.png">

<img width="737" alt="Screenshot 2023-01-20 at 14 05 52" src="https://user-images.githubusercontent.com/47140236/213691250-fc3a9369-e157-456d-9e9e-95e85063292b.png">

**Comment by jcesarmobile** [comment]
Closing as this is not an issue but a question.

You can ask questions on the [Ionic Forums](https://forum.ionicframework.com/c/capacitor/26) or on the [discussions section](https://github.com/ionic-team/capacitor/discussions) of capacitor repository
