### ISSUE TITLE
Choose the name of the starting HTML file in webDir

### ISSUE THREAD

**Issue by marclou** [ionic-team/capacitor-docs#153]
Most apps I build with Capacitor have a landing page + the app itself.

When I ship the app, I wish it would directly load the app.html or dashboard.html instead of the index.html (the landing page, usually)

For now, I do some routing in useEffect as a fix. But the user sees the landing page for a few ms.

It would be dope to be able to choose which HTML file the app opens.

Thanks!

**Comment by jcesarmobile** [comment]
This is the docs repository, should only be used for reporting issues on the docs
there is a capacitor ticket about this feature already, you can subscribe to it
https://github.com/ionic-team/capacitor/issues/3912
