### ISSUE TITLE
Capacitor plugin import format outdated

### ISSUE THREAD

**Issue by donaldchada** [ionic-team/capacitor-docs#203]
I just realised that in some parts of capacitor 5 documentation  there are outdated info
Eg importing plugins like status bar 

Instead of import {Camera} from "@capacitor/core"

Its still 
import {Camera} from "@capacitor/camera"
Advice if thats correct

**Comment by jcesarmobile** [comment]
Can you provide links to those docs?
I can't find any other than the Capacitor 2 docs that we still host at `https://capacitorjs.com/docs/v2/plugins`.

**Comment by jcesarmobile** [comment]
closing due to the lack of response
