### ISSUE TITLE
Missing Crucial Information To Send JSON Data With CapacitorHttp

### ISSUE THREAD

**Issue by Ryan-Rante** [ionic-team/capacitor-docs#232]
**URL**
[Capacitor Official Plugins HTTP](https://capacitorjs.com/docs/apis/http)

**What is missing or inaccurate about the content on this page?**
I only found the issue at Android platform. The API server does not receive JSON data if you try to request it without explicity send header `Content-Type` `application/json`.

I have read the Java base code and it actually skips the process of writing data if you try to request data without `Content-Type` header.

If you want to send data JSON with Android platform, you need to add header `Content-Type` with `application/json` like this.
```ts
const ret = await CapacitorHttp.post({
    ...
    data: {
        message: 'Hello World!'
    },
    headers: {
        "Content-Type": "application/json"
    },
    ...
});
```

For other type of data, if I had time, I would try one by one.

**Comment by jcesarmobile** [comment]
This is a bug in the plugin, not in the docs
https://github.com/ionic-team/capacitor/issues/7245
