### ISSUE TITLE
Incorrect information in the Android push message setup guide

### ISSUE THREAD

**Issue by Pentadome** [ionic-team/capacitor-docs#316]
**URL**
https://capacitorjs.com/docs/guides/push-notifications-firebase#download-and-use-the-google-servicesjson-file

**What is missing or inaccurate about the content on this page?**

>We don't need to add any dependencies to our project because Capacitor projects automatically include a version of firebase-messaging in it's build.gradle file.

This is not true, you need [to add the firebase sdk](https://firebase.google.com/docs/android/setup#add-sdks) or it doesn't work.

**Comment by jcesarmobile** [comment]
I've just follow the guide and it works without adding the SDK. 
By installing `@capacitor/push-notifications` you get the dependency.
