### ISSUE TITLE
Angular production mode and Capacitor 6 plugins throw error code UNIMPLEMENTED on iOS

### ISSUE THREAD

**Issue by xbisa** [ionic-team/capacitor-docs#325]
**Describe the bug**
I'm using local-notifications and toast Capacitor plugins v6 in my iOS app.
Works for development, test and staging Angular configurations.

**To reproduce**
You need an Angular app v17, add Capacitor to it, install an NPM Capacitor plugin (e.g. add local-notifications and call the API method await LocalNotifications.requestPermissions() on init), build your Angular app for production, make a simulation build for iOS.

**Expected behavior**
Capacitor plugins are enabled.

**Browser and OS
 - OS: iOS

**Additional context**
No problems on Android

**Comment by jcesarmobile** [comment]
This is the documentation repository, doesn't look like a problem with the documentation. 

Create a new issue on https://github.com/ionic-team/capacitor/issues and please, provide a sample app that reproduces the issue

**Comment by faguilera85** [comment]
I'm facing the same issue with "@capacitor-community/admob": "^6.0.0". When I call await AdMob.initialize(); I get {"code":"UNIMPLEMENTED"} in the Xcode logs using the simulator on iPhone 15 Pro (iOS 17.4).
I really need help to understand how to proceed please, I've been blocked for more than a week already.

**Comment by nocteryals** [comment]
I am experimenting the same issue @faguilera85 did you find a solution?

**Comment by jhonnathanH** [comment]
I have the same issue..
I had a custom plugin in capacitor 5
now in capacitor 6, I get this error `UNIMPLEMENTED `

anyone know how to link/register the plugin in capacitor 6??.. the doc it's wrong

**Comment by nocteryals** [comment]
On my side i solved the issue moving to capacitor 5 again. anything more works.
