### ISSUE TITLE
Recommended way to use private repo 

### ISSUE THREAD

**Issue by tyange-ph** [ionic-team/capacitor-docs#60]
to @capacitor team, I'd like to know what do you suggest if I am using private repo?
Our team is planning to use capacitor but I we have few issues facing with gradle dependencies.

Appreciate if you can give some suggestions. Thank you

**Comment by jcesarmobile** [comment]
This repository is for reporting bugs on the documentation.
If you need help you can ask on the forum
https://forum.ionicframework.com/c/capacitor/26
or in GitHub discussions
https://github.com/ionic-team/capacitor/discussions

Would be good if you could provide more information there as with the information you have provided here nobody is going to be able to help you.
